# TODO: Publish the image as a cron job
name: Check & Publish
on: [push, pull_request]
jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Format and check with shfmt
        uses: bltavares/actions/shfmt@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_ARGS: -i 2 -ci
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint docker file (docker-lint)
        uses: docker://cdssnc/docker-lint-github-action
        with:
          args: --ignore DL3007 --ignore DL3018
  # TODO: Only publish on master/tagged push
  build:
    runs-on: ubuntu-latest
    needs: [shfmt, lint]
    steps:
      - uses: actions/checkout@master
      - name: Build & Publish
        run: |
          ./docker-base/update.sh
        env:
          PUBLISH_IMAGE: ${{github.ref == 'refs/heads/master'}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
